config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: "login", sign_out: "logout", sign_up: 'register'}
  resources :portfolios, except: [:show]
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  root 'pages#home'

  get 'about', to: 'pages#about'
  get 'contact', to:  'pages#contact'

#  get 'blog/:id/toggler', to: 'blogs#toggler', as: "togler-status"

  resources :blogs do
    member do
      get :toggle_status
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  include Placeholder

  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                reject_if: lambda {|attrs| attrs['name'].blank?}

  validates_presence_of :title, :body, :main_image, :thumb_image

  def self.angular
    where(subtitle: 'Angular')
  end

  scope :ruby_on_rails_portfolio_items, -> {where(subtitle: 'Ruby on Rails')}

  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: 600,width: 400)
    self.thumb_image ||= Placeholder.image_generator(height: 350,width: 200)
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [:edit, :update, :show, :destroy]
  layout "portfolio"
  access all: [:show, :index, :angular], user: {except: [:destroy,:new, :create, :update, :edit]}, site_admin: :all

  #only index,new, and create doesn't need id at first
  def index
    @portfolio_items = Portfolio.all
  end

  def angular
    @angular_items = Portfolio.angular
  end

  def show
  end

  def new
    @portfolio = Portfolio.new
    3.times { @portfolio.technologies.build}
  end

  def create
    @portfolio = Portfolio.new(portfolios_params)
    respond_to do |format|
      if @portfolio.save
        format.html {redirect_to portfolios_path, notice: "Your portfolio was created"}
      else
        format.html {render :new}
      end
    end
  end

  def edit
    3.times { @portfolio.technologies.build}
  end

  def update
    respond_to do |format|
      if @portfolio.update(portfolios_params)
        format.html {redirect_to portfolios_path, notice: "Your portfolio was updated"}
      else
        format.html {render :edit}
      end
    end
  end

  def destroy
    @portfolio.destroy
    respond_to do |format|
       format.html {redirect_to portfolios_path, notice: "Your portfolio was deleted"}
    end
  end

  private
  def portfolios_params
    params.require(:portfolio).permit(:title,
                                      :subtitle,
                                      :body,
                                      technologies_attributes: [:name]
                                    )
  end

  def set_portfolio_item
    @portfolio = Portfolio.find(params[:id])
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(portfolio) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <ul>
    <%= form.fields_for :technologies do |technology_form| %>
      <li>
        <%= technology_form.label :name %>
        <%= technology_form.text_field :name %>
      </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
<p><%= portfolio_item.subtitle %></p>
<p><%= portfolio_item.body %></p>
<%= image_tag portfolio_item.thumb_image if portfolio_item.thumb_image %>
<%= link_to "Edit", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %>
<%= link_to "Delete", portfolio_path(portfolio_item), method: :delete, data: {confirm: 'Are your sure?'} if logged_in?(:site_admin)%>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<a href="portfolios/new">Create New User</a>
<%= link_to "Create new portfolio", new_portfolio_path if logged_in?(:site_admin)%>
<%= link_to "Create new portfolio", new_portfolio_url, subdomain: "my_subdomain" if logged_in?(:site_admin)%>

<% @angular_items.each do |portfolio| %>
  <p><%= link_to portfolio.title, portfolio_show_path(portfolio) %></p>
  <p><%= portfolio.subtitle %></p>
  <p><%= portfolio.body %></p>
  <%= image_tag portfolio.thumb_image if portfolio.thumb_image %>
  <%= link_to "Edit", edit_portfolio_path(portfolio) if logged_in?(:site_admin)%>
  <%= link_to "Delete", portfolio_path(portfolio), method: :delete, data: {confirm: 'Are your sure?'} if logged_in?(:site_admin)%>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Edit portfolio</h1>

<%= render 'form', portfolio: @portfolio %>

app/views/portfolios/index.html.erb
<h1>Portfolio Items</h1>

<%= link_to "Create Portfolio", new_portfolio_path if logged_in?(:site_admin)%>

<%= render partial: 'portfolio_item', collection: @portfolio_items %>

app/views/portfolios/new.html.erb
<h1>Create a new portfolio item</h1>

<%= render 'form', portfolio: @portfolio %>

app/views/portfolios/show.html.erb
<%= image_tag @portfolio.main_image if @portfolio.main_image%>

<h1>Show your portfolio</h1>

<em><%= @portfolio.title %></em>
<em><%= @portfolio.subtitle %></em>
<em><%= @portfolio.body %></em>

<h2>Techonologies Used:</h2>

<% @portfolio.technologies.each do |technology| %>
  <p><%= technology.name %></p>
<% end %>